mozilla/terraform-modules

.github/workflows/ci.yaml, google_project/README.md, google_project/locals.tf, google_project/main.tf, google_project/variables.tf
Jira: https://mozilla-hub.atlassian.net/browse/OPST-227
=> OPST-227: adding default google_project_service to google_project module

google_redis/README.md, google_redis/examples/example1.tf, google_redis/variables.tf
Following the region example from #20
=> Setting redis region var to null and updating example

google_project/README.md
Forgot to update this from #23
=> Updating README for google_projects

google_gke/locals.tf
A better fix replacing https://github.com/mozilla/terraform-modules/pull/26
=> Using the project_id variable directly rather than trimming the id

README.md, aws_itse-roles/README.md, aws_itse-roles/versions.tf, google_project-dns/README.md, google_project-dns/versions.tf, google_tfstate/README.md, google_tfstate/versions.tf
- readme: Update terraform-docs command
- aws_itse-roles: Relax version constraints
- google_project-dns: Relax version constraints
- google_tfstate: Relax version constraints
=> terraform: Relax version constraints

google_cloudsql_mysql/README.md, google_cloudsql_mysql/examples/minimal/main.tf, google_cloudsql_mysql/examples/more/main.tf, google_cloudsql_mysql/main.tf, google_cloudsql_mysql/variables.tf, google_cloudsql_mysql/versions.tf
Jira: https://mozilla-hub.atlassian.net/browse/OPST-590
This PR does the following:
* Updates labels to conform to our standard required labels
* Fix version in google provider
* Fixed examples source url
* Regenerated docs
=> Update required labels in terraform modules

google_gar/main.tf, google_memcache/main.tf, google_memcache/variables.tf, google_redis/main.tf, google_redis/variables.tf
Jira: https://mozilla-hub.atlassian.net/browse/OPST-590
This PR conforms the label names to our required labels and adds `component_code` where it is necessary.
=> Update required labels in terraform modules (gar, memcache, redis)

google_gke/README.md, google_gke/cluster.tf, google_gke/locals.tf, google_gke/variables.tf
Jira: https://mozilla-hub.atlassian.net/browse/OPST-643
Tested with new shared clusters. This provides the ability to pass a Google Group to be used for RBAC inside the cluster.
=> google_gke: Adding google group security group variable

google_workgroup/.terraform-docs.yml, google_workgroup/README.md, google_workgroup/examples/example1.tf, google_workgroup/main.tf, google_workgroup/outputs.tf, google_workgroup/variables.tf, google_workgroup/versions.tf
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-682
r?
=> google_workgroup: add workgroup module OPST-682

google_gke_tenant/secret_manager.tf
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-722
Since we are enabling the GSM service it seems right to do it here.
=> google_gke_tenant: enable GSM audit logs

google_memcache/main.tf
Fix for https://github.com/mozilla-it/webservices-infra/pull/35
=> adding dynamic block to memcache_parameters

google_cdn-external/README.md, google_cdn-external/main.tf, google_cdn-external/variables.tf, google_cdn-external/versions.tf
Adds optional compression and adds optional negative caching
=> Cdn enhancements

google_cdn-external/README.md, google_cdn-external/main.tf, google_cdn-external/variables.tf
=> google_cdn-external: add quic_override policy

google_project/README.md, google_project/locals.tf, google_project/variables.tf
Updated the locals and variables files to add risk_level as a label
=> Added risk_level as a label variable

google_memcache/README.md, google_memcache/main.tf, google_memcache/variables.tf, google_memcache/versions.tf
Add the mainenance_policy and refresh the terraform version.
=> Update the google_memcache module

google_redis/README.md, google_redis/main.tf, google_redis/variables.tf
=> google_redis: add persistence configuration

google_project/main.tf
Added a resource to enable data access logs if the project has a risk level label of high
=> feat(google_project): Data access logging

google_project/main.tf
Let me know how this looks, I wasn't sure what the @type should be for secretmanager or iam so I tried to use serviceName which I believe should work. I didn't make this conditional on the risk level, so every project would get this exclusion, regardless of whether the logs exist or not.
=> feat(google_project): Data access logging exclusion

google_project/main.tf
=> fix(google_project): do not exclude sts logs from project logging

google_gke/README.md, google_gke/cluster.tf, google_gke/variables.tf, google_gke/versions.tf
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-1037
To support https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
r?
=> feat(google_gke): add gcs_fuse_csi_driver_config addon configuration

google_gke/cluster.tf
Add support for GPU node pools https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#cos
=> feat: Add GPU configuration for shared GKE cluster module

google_cloudsql_postgres/main.tf, google_cloudsql_postgres/variables.tf
Allow the replica to have insights and a regional deployment
=> feat(postgres): Replica configuration

CODEOWNERS, README.md
=> fix(codeowners): update entries to remove charlow and kkleemola 

google_gke/cluster.tf
I missed up and gave https://github.com/mozilla/terraform-modules/pull/133 the wrong title to get a release
=> feat: Allow more configuration options for GKE Guest Accelerator

google_psc_to_elastic/README.md, google_psc_to_elastic/main.tf, google_psc_to_elastic/variables.tf, google_psc_to_elastic/versions.tf
Add this feature to support https://github.com/mozilla-it/global-platform-admin/pull/887
=> feat: Allow the "google_compute_network" data source to pull from specified project

google_project/locals.tf
Service health is the new hotness for viewing incidents within projects.
r?
=> feat(google_project): enable servicehealth on projects

CODEOWNERS
Updating codeowners to match other core modules.
=> fix(codeowners): updated entries for google_gke codeowners

google_project/main.tf
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-1279
We already manage the "_Default" bucket, this adds "_Required".
r?
=> feat(google_project): add log analytics support for _Required

google_permissions/other_roles.tf, google_permissions/outputs.tf
add_role_aiplatform.colabEnterpriseUser to the google permission module.
=> fix(google_permissions): add_new_additional_role

google_gke/cluster.tf
To help with debugging issues.
r?
=> feat(google_gke): enable control plane logging components

google_project-dns/README.md, google_project-dns/variables.tf
=> fix(google_project-dns): add security to validation

CODEOWNERS, google_deployment_accounts/examples/circleci3.tf
Fix extra `/` appearing in the example.
=> chore(deployments_accounts): Fix typo in example.

google_project/README.md, google_project/main.tf
makes destroying projects too complicated
=> chore(google_project): removing prevent_destroy=true

google_gke/variables.tf
https://mozilla-hub.atlassian.net/browse/OPST-1169
=> feat(gke): Add GKE managed kube-state metrics

google_gke_tenant/gke_service_account.tf
Added a new workload identity binding for generic service accounts.
=> feat(google_gke_tenant): added workload identity for generic k8s service account

google_cloudsql_mysql/README.md, google_cloudsql_mysql/main.tf, google_cloudsql_mysql/variables.tf, google_cloudsql_postgres/README.md, google_cloudsql_postgres/main.tf, google_cloudsql_postgres/variables.tf
Work around https://github.com/hashicorp/terraform-provider-google/issues/15227
=> fix(google_cloudsql): Fix data_cache_config perma-diff

google_cloudsql_mysql/README.md, google_cloudsql_mysql/main.tf, google_cloudsql_mysql/variables.tf, google_cloudsql_postgres/README.md, google_cloudsql_postgres/main.tf, google_cloudsql_postgres/variables.tf
- **chore(google_cloudsql_mysql): Update documentation for query_insights_enabled**
- **feat(google_cloudsql_mysql): Add connector_enforcement variable for Cloud SQL Auth Proxy**
- **feat(google_cloudsql_postgres): Add connector_enforcement variable for Cloud SQL Auth Proxy**
=> feat(google_cloudsql): Add connector_enforcement variable for Cloud SQL Auth Proxy

google_cloudsql_mysql/README.md, google_cloudsql_mysql/main.tf, google_cloudsql_mysql/variables.tf, google_cloudsql_mysql/versions.tf, google_cloudsql_postgres/README.md, google_cloudsql_postgres/main.tf, google_cloudsql_postgres/variables.tf
- **fix(google_cloudsql_mysql): Remove deprecated require_ssl argument**
- **fix(google_cloudsql_postgres): Remove deprecated require_ssl argument**
=> fix(google_cloudsql): Remove deprecated require_ssl argument

google_project/locals.tf
added GCP PAM to default project services to be enabled for all projects
=> feat: enabled GCP PAM in default project services

google_project/main.tf
```
The Argument skip_delete is deprecated and will be removed in 6.0.0. 
and is replaced by the argument deletion_policy 
```
=> fix(module):google_project_module_update_skip_delete_arg

google_project/versions.tf
```
update the google provider version
```
=> fix: update the google provider version

google_project/main.tf, google_project/variables.tf, google_project/versions.tf
```
change the value of the deletion_policy to PREVENT if the project name contains Bastion 
```
=> Opst 1770 

google_project/variables.tf
_policy to PREVENT
```
update the default value of deletion_policy to PREVENT
```
=> fix: update the deletion

google_project/locals.tf
```
added cloudasset API to default project services in bootstrap
```
=> chore(OPST-1812): added cloudasset API to default project services in bootstrap

.github/workflows/ci.yaml
```
Install terraform as part of the Github Action.
```
=> fix(terraform): Install terraform

google_project/locals.tf
```
added PAM/Privileged Access Manager API to default audit logging list in terraform
```
=> chore(google_project) - added PAM API to default audit logging list in terraform

.github/actions/action.yml
```
fix(ci): Correct reference to GitHub token
```
=> fix(ci): Correct reference to GitHub token

.github/actions/action.yml, google_gke_namespace_logging/README.md, google_gke_namespace_logging/outputs.tf
This is needed for teams needing to change the default permissions on
the linked BigQuery dataset.
```
feat(google_gke_namespace_logging): Output linked BigQuery dataset ID
```
=> feat(google_gke_namespace_logging): Output linked dataset ID

google_gke/README.md, google_gke/outputs.tf
```
feat(google_gke): Output cluster id
```
=> feat(google_gke): Output cluster id

google_gke_namespace_logging/README.md, google_gke_namespace_logging/outputs.tf
```
chore(google_gke_namespace_logging): Add description for output
```
=> chore(google_gke_namespace_logging): Add description for output

google_permissions/ADDING_NEW_ROLE.md, google_permissions/Design.md
```
Run pre-commit to fix trailing whitespace
```
Will also generate 0.0.3 tag which should have come with https://github.com/mozilla/terraform-modules/pull/267, now that https://github.com/mozilla/terraform-modules/pull/269 is merged
=> chore:run pre-commit

google_fastly_waf/provider.tf, google_fastly_waf/variables.tf
```
Update Fastly module to not require corp or email variables
```
=> Fastly waf updates

google_fastly_waf/versions.tf
```
chore: Allow Terraform provider google v6
```
=> chore(google_fastly_waf): Allow Terraform provider google v6

.github/actions/action.yml
I believe I broke the tag interpolation as can be seen in the latest release https://github.com/mozilla/terraform-modules/tags
=> fix: Correctly interpolate the variable

google_certificate_manager_certificate_map/README.md, google_certificate_manager_certificate_map/outputs.tf, google_certificate_manager_certificate_map/service.tf
```
Output DNS authorization records
Enable certificatemanager API
```
=> feat(certificate_map): Output DNS authorization records

.github/actions/action.yml, .github/workflows/ci.yaml, .github/workflows/monorepo.yml
```
Update some github actions to reflect new Zizmor rules
```
=> fix(zizmor): Update based on new zizmor rule

google_fastly_waf/main.tf
```
Add explicit backend link
```
=> fix(fastly): Add explicit link with backend

google_permissions/workgroups.tf
```
* fix source paths for `mozilla_workgroup` sub-modules in `google_permissions` module
```
=> fix(google_permissions): fix mozilla_workgroup module source

google_fastly_waf/main.tf, google_fastly_waf/variables.tf
```
Allow passing in snippets for easy VCL modification
```
=> feat(fastly): Allow passing in snippets to modify VCL

google_bigquery_log_sink/README.md, google_bigquery_log_sink/main.tf, google_bigquery_log_sink/variables.tf
```
Adds various overrides to bq log sink module to support v1 migrated infra
```
For https://mozilla-hub.atlassian.net/browse/SVCSE-2708
=> feat:add override vars to bq log sink module

google_fastly_waf/.terraform-docs.yaml, google_fastly_waf/README.md, google_fastly_waf/examples/example.tf, google_fastly_waf/examples/example_maintenance_page.tf, google_fastly_waf/main.tf, google_fastly_waf/variables.tf
```
The combination of a condition and response_object will allow you to serve a static maintenance page, or custom error responses, through Fastly.
```
=> feat(fastly): Dynamic condition and response_object

.github/actions/action.yml
Failed here https://github.com/mozilla/terraform-modules/actions/runs/15930398016/job/44937921858?pr=316
=> fix(zizmor): Add persist credentials to actions

google_cloudsql_mysql/README.md, google_cloudsql_mysql/examples/psc/main.tf, google_cloudsql_mysql/main.tf, google_cloudsql_mysql/variables.tf, google_cloudsql_postgres/README.md, google_cloudsql_postgres/examples/psc/main.tf, google_cloudsql_postgres/main.tf, google_cloudsql_postgres/variables.tf
```
Add variables for Query Insights to match mysql module
```
=> feat(google_cloudsql_postgres): Add variables for Query Insights to match mysql module

.github/actions/action.yml, .github/workflows/monorepo.yml
Removes broken changelog generation steps from CI
* https://github.com/mozilla/terraform-modules/actions/runs/16506059897/job/46676863038?pr=325
=> fix:rm changelog generation

google_fastly_waf/main.tf
Add one more dependency to the list.
=> fix(fastly): Add a depends to the edge site definition

google_fastly_waf/bigquery.tf, google_fastly_waf/gcs.tf
Trying to set some better labels for GCP logging artifacts created from module. Eventually this can be merged with the labels from the provider.
=> fix(fastly): Add better labels for GCP log components

.github/workflows/monorepo.yml
Fix paths to composite GHAs
* MZCLD-880
=> fix(ci): fix gha paths
