mozilla/terraform-modules

- google_project/README.md
- google_project/locals.tf
- google_project/variables.tf
As part of the discussion https://github.com/mozilla/terraform-modules/pull/2#discussion_r755407063, I didn't clearly specify that we needed to keep the realm label. 
I believe only https://github.com/mozilla-it/global-platform-admin/blob/ac672e3eef0fd51054ddb991f1bab6f47d89b51e/shared/tf/projects.tf#L22-L32 is referring to this now and I will submit a PR for the change.
r?
> google_project: add realm variable OPST-84

- google_project/locals.tf
Jira: Came up in context of https://mozilla-hub.atlassian.net/browse/OPST-333
What this PR does:
* @jasonthomas added back in realm variable to this module in a previous PR (#6 ) 
* with that added back in, need to add the interpolation for the default project_name to be project_name plus realm
* still leaving out env_code and environment variables, since seems to only be used as labels to replicate value of realm
> with realm variable added, update local.project_name

- google_project/README.md
- google_project/outputs.tf
project number is useful in the context of provisioning shared vpc subnet resources and IAM permissions. 
r?
> google_project: include project_number in outputs

- google_project/locals.tf
Jira: came up in context of https://github.com/mozilla-it/global-platform-admin/pull/63
What this PR does:
* adds cloudbilling.googleapis.com to default APIs to be enabled on any GCP project
* enabling this API allows us to associate the billing account ID to the project
> add cloudbilling to default GCP project enabled services

- google_workload_identity/.terraform.lock.hcl
- google_workload_identity/versions.tf
Jira: Came up in context of https://mozilla-hub.atlassian.net/browse/OPST-453
What this PR does:
* updates the GCP workload identity module to hashicorp/google provider version 4.0 & above. 
* we started updated our providers in other modules (see gke) so this helps keep consistency for tf projects using both modules
> update google provider version constraint for workload id

- google_gar/README.md
- google_gar/examples/README.md
- google_gar/examples/example.tf
- google_gar/main.tf
- google_gar/outputs.tf
- google_gar/variables.tf
- google_gar/versions.tf
I tested this with a newly created project. It took a while for the relevant API to get enabled, and I had to add an explicit dependency for that to work correctly, but now I believe everything is working as intended.
I did not add an environment label, since we don't plan to have more than one registry per project. As discussed in the last meeting between Jason and me, we may even only want a single repository per app, so maybe we want to remove the realm label as well.
https://mozilla-hub.atlassian.net/browse/OPST-378
> Add Google Artifact Registry module.

- google_gke_tenant/gke_service_account.tf
Looks like using `..._iam_binding` clashes with tenant bindings if they want to use workload identity, so they should both use `...iam_member`
> changing iam_binding to iam_member

- aws_gcp_vpn/README.md
- aws_gcp_vpn/main.tf
- aws_gcp_vpn/variables.tf
This is required to allow connecting to GCP services using peer vpc networks such as CloudSQL
> aws_gcp_vpn: Add variable for custom route advertisements

- google_cdn-external/README.md
- google_cdn-external/main.tf
- google_cdn-external/variables.tf
- google_cdn-external/versions.tf
This PR copies `google-cdn-external` from [cloudops-infra-terraform-modules](https://github.com/mozilla-services/cloudops-infra-terraform-modules). It will be used in [webservices-infra/data-static-websites](https://github.com/mozilla-it/webservices-infra/tree/main/data-static-websites)
I was thinking about linking this modules as a git submodule in [cloudops-infra-terraform-modules](https://github.com/mozilla-it/webservices-infra/tree/main/data-static-websites) so we don't have to maintain both modules. Looking for feedback on this
> feat: copy google-cdn-external from cloudops-infra-terraform-modules

- google_cdn-external/README.md
- google_cdn-external/main.tf
- google_cdn-external/variables.tf
This PR makes `var.name` optional and removes `var.realm` since it's unused.
Once this is merged, related PR needs to be updated to point at `main` instead of a specific commit SHA.
https://github.com/mozilla-it/webservices-infra/pull/141
> feat(cdn-external): make var.name optional and remove unused var.realm

- google_cloudsql_mysql/README.md
- google_cloudsql_mysql/main.tf
- google_cloudsql_mysql/variables.tf
A few of the services we run have more load on the replica instances and require different instance types for their replicas. 
* added separate config for replica cpu/memory 
* set replica `availability_type` to match primary instance
> Added separate config for replica instances

- google_gke/README.md
- google_gke/cluster.tf
- google_gke/variables.tf
- google_gke/versions.tf
“Managed Service for Prometheus will be on by default in new GKE standard clusters”. This is so we can start rolling it out on our shared clusters. 
r?
> feat(google_gke): add monitoring_enable_managed_prometheus flag

- google_gke/variables.tf
Moves `additional_ip_ranges` map to conform with the actual VPC output.
r?
> feat(google_gke): fix shared_vpc_outputs

- google_cdn-external/README.md
- google_cdn-external/main.tf
- google_cdn-external/variables.tf
This adds support for Google Cloud CDNs with bucket backends. The backend type defaults to `service` so downstream modules already consuming this module should not see any changes.
Documentation for `google_compute_backend_bucket` resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket
**Note**: I opted to make certain resources optional using `count` instead of `for_each`. Using `for_each` required manual modifications to the Terraform state file whereas Terraform modified the state automatically when using `count`.
This is a port of recent changes to https://github.com/mozilla-services/cloudops-infra-terraform-modules/tree/OPST-831/google-cdn-external where this functionality was initially implemented to support the Taskcluster …
> feat(google_cdn-external): add support for bucket backends

- google_datastream/.readme-header.yml
- google_datastream/.terraform-docs.yml
Storing the content in a separate file and including it in `.terraform-docs.yml` seems to do the trick.
> fix(google_datastream): README indentation

- google_deployment_accounts/main.tf
- google_deployment_accounts/variables.tf
The default deployment service accounts, i.e. deploy-{dev,stage,prod}, are each tied to a specific environment. Therefore, they can only deploy from the respective tied environment. However, there are instances where we need to deploy from multiple environments using the same service account. This pull request aims to address this specific use case.
> feat: allow deployments from multiple Github environments

- google_redis/main.tf
We ran into the same issue documented in https://github.com/hashicorp/terraform-provider-google/issues/11871 This PR adds a workaround to the issue.
> fix: 400 error when updating existing redis instances

- google_cloudsql_mysql/README.md
- google_cloudsql_mysql/main.tf
- google_cloudsql_mysql/variables.tf
- Added support to optionally enable private path for Google Cloud Services (ie. BigQuery)
- `enable_private_path_for_google_cloud_services`: Enables setting for primary instance and replica instance(s), if replicas are enabled -- default `false`
- `replica_enable_private_path_for_google_cloud_services`: Overrides the above for replica instance(s) -- default `null`
- With these settings disabled by default, existing CloudSQL MySQL instances should not be impacted by this change
- Fixed some variable descriptions as `terraform-docs` was removing stuff from the README that wasn't included in the variable descriptions
- Added descriptions for variables that didn't have any
In a project, I manually enabled this setting for enabling private paths for Google Cloud services on a replica DB …
> feat(google_cloudsql_mysql): optionally enable private path for Google Cloud Services

- google_cloudsql_postgres/README.md
- google_cloudsql_postgres/main.tf
- google_cloudsql_postgres/variables.tf
We need more flexibility for the SUMO database replica configuration. All settings added here already exist in the MySQL module. I kept the code as close to the code in that module as possible.
As a side note, there is a lot of code duplication between the MySQL and Postgres module. I think we should create a single `google_cloudsql` module supporting both databases and deprecate the old modules. (We could also add implementations for the old modules that simply forward to the new one.)
> google_cloudsql_postgres: Expose more replica settings.

- google_project-dns/variables.tf
We are working on spinning up a new sandbox shared cluster, this module is consumed by the bootstrapping process and a new sandbox team should be an option to keep things in line with other cluster resources.
> feat(google_project-dns): Added sandbox as a new team_name option

- mozilla_workgroup/README.md
- mozilla_workgroup/main.tf
- mozilla_workgroup/outputs.tf
- mozilla_workgroup/variables.tf
- mozilla_workgroup/versions.tf
We maintain a shim workgroup module in the *-infra repos to make it easier to reference workgroups. This means that this code is duplicated in several repos, and there is now drift. As part of consolidating permissions process and module, we will migrate workgroup module from the old location into this common one.
> feat(mozilla workgroup): OPST-1098 - Migrate internal workgroup to terraform-modules

- google_gke/k8s_api_proxy.tf
- google_gke/variables.tf
Added the option to reserve a static internal IP address for each cluster. 
This is intended for the k8s api proxy service running in each cluster but could be used elsewhere.
> feat(google_gke): enable internal ip reservation for k8s api proxy

- google_gke/k8s_api_proxy.tf
- google_gke/variables.tf
Updating `internal_lb_subnetworks` to `service_subnetworks` variable to better reflect what we need here. 
This static IP address will be consumed via internal service which needs to be within the cluster service subnet range and not the internal lb subnetworks provisioned for internal gateway services.
> fix(google_gke): updating service_subnetworks variable

- google_gke/k8s_api_proxy.tf
- google_gke/locals.tf
- google_gke/outputs.tf
- google_gke/variables.tf
Creating new DNS records in the cluster DNS zone for the `k8s-api-proxy` service. 
Need to pass in project outputs to this module to pull DNS zone information.
> feat(google_gke): create dns record for k8s-api-proxy ip address

- google_gke/variables.tf
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-1270
To enable [control plane metric collection](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-metrics#control-plane-metrics) on our clusters.
r?
> feat(google_gke): add additional control plane metrics collection as

- google_permissions/other_roles.tf
- google_permissions/outputs.tf
while working on https://mozilla-hub.atlassian.net/browse/OPST-1261 , I started by modifying moz-soc https://github.com/mozilla-it/dataservices-infra/pull/254 . 
needed an additional roles to be added to the validated list.
> fix(google_permissions): add roles/pubsub.editor to project_additional_roles

- google_gar/locals.tf
- google_gar/main.tf
- google_project-dns/README.md
- google_project-dns/locals.tf
I was getting some errors when creating a tenant that starts with a digit. It seems like some GCP resources cannot be created with the first character as a digit. This removes the digit match which
> feat(tenant): Allow tenant to start with number

- google_gke/versions.tf
Via release notes https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.82.0
In particular, https://github.com/hashicorp/terraform-provider-google/pull/15727/files
> fix(gke): Minimal version bump to pull in changes for state metrics

- google_cloudsql_mysql/variables.tf
While working on a PR I discovered that the postgres module enables query insights by default, but the mysql module disables them by default.
Given that enabling query insights does not require a restart, and the information is very useful for debugging database performance issues I decided to enable them by default.
> feat(google_cloudsql_mysql): Enable query insights by default

- google_cloudsql_postgres/variables.tf
This issue prevented me from deploying: https://github.com/mozilla-it/webservices-infra/pull/2654#issuecomment-2326543360
In Terraform, the logical or operator `||` does not short-circuit. As a result, the second part of the validation condition gets evaluated even when `connector_enforcement` is `null`, and for some reason that's not a valid second parameter to `contains()` (which makes no sense, but it is how it is).
> fix(google_cloudsql_postgres): Allow null values for connector_enforcement.

- google_monitoring/README.md
- google_monitoring/uptime_checks.tf
- google_monitoring/variables.tf
As part of [OBS-191](https://mozilla-hub.atlassian.net/browse/OBS-191), I am writing a ["How to create an uptime check"](https://docs.google.com/document/d/1Q9BW41-hhHwt03uOsm4oKYUoJdmsxPGkPrpOcwmuNco/edit?usp=sharing) document.
One common use case we expect is for teams to only care about checks for a subset of all the global regions a Google Uptime Check checks from by default (e.g. maybe they only need checks from `"USA"` and `"EUROPE"`, and not from `"SOUTH_AMERICA"` or `"ASIA_PACIFIC"`). Since each checker costs us executions, it makes sense to have this option, so I've added it here.
I've tested it in https://github.com/mozilla-it/webservices-infra/pull/2698.
> feat(google_monitoring): add selected_regions option to uptime check

- google_gke/cluster.tf
We ran into an issue where a node pool was going to be [recreated](https://github.com/mozilla-it/global-platform-admin/pull/1143), could have been related to a manual node pool change via the UI. It's [recommended](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#initial_node_count) to ignore initial_node_count as part of the lifecycle policy. 
r?
> fix(google_gke): ignore initial_node_count in node pool lifecycle block

- .github/pull_request_template.md
- .releaserc.yaml
Add PR template that was meant to be included in https://github.com/mozilla/terraform-modules/pull/237
Clean up no longer needed releaserc.yaml.
> fix: add missing pr template

- .github/workflows/actions/action.yml
Replace `git commit`s in GHA workflow with `gh api` request.
Commits done by a bot user via git commit don't get signed (https://github.com/actions/runner/issues/667), but they do get signed if they're submited via `gh api`. Since we require signed commits for this repo, and github doesn't provide a good way to sign commits with bot users, we need to use the API.
Validated in https://github.com/amitchell-moz/module-versioning-ci-test (LKM if you want an invite)
> use API to commit in GHA doc steps so commits get signed

- aws_gke_oidc_config/.terraform-docs.yml
- aws_gke_oidc_config/CHANGELOG.md
- aws_gke_oidc_config/README.md
- aws_gke_oidc_config/examples/main.tf
- aws_gke_oidc_config/main.tf
- aws_gke_oidc_config/variables.tf
- aws_gke_oidc_config/versions.tf
- aws_gke_oidc_role/.terraform-docs.yml
- aws_gke_oidc_role/CHANGELOG.md
- aws_gke_oidc_role/README.md
- aws_gke_oidc_role/examples/role_and_config/main.tf
- aws_gke_oidc_role/examples/role_and_config/providers.tf
- aws_gke_oidc_role/examples/role_with_policy/main.tf
- aws_gke_oidc_role/examples/role_with_policy/providers.tf
- aws_gke_oidc_role/main.tf
- aws_gke_oidc_role/outputs.tf
- aws_gke_oidc_role/variables.tf
- aws_gke_oidc_role/versions.tf
Add modules to provision AWS roles + OIDC configs to allow GKE workloads to assume AWS roles.
https://mozilla-hub.atlassian.net/browse/OPST-1509
This PR introduces 2 modules:
aws_gke_oidc_config
creates an OIDC provider in AWS to setup a trust relationship between a cluster & AWS account
aws_gke_oidc_role
creates AWS roles that use the trust relationship established by ^^ to allow GKE service accounts to assume AWS roles
These need to be separate modules because the OIDC provider URL must be unique per-account, but a given GKE cluster only has 1 OIDC endpoint. That means the OIDC provider tf must only be ran once, after that any number of roles can use it.
```
add aws_gke_oidc_config and aws_gke_oidc_role modules
```
> feat: add aws_gke_oidc_config and aws_gke_oidc_role modules

- .github/actions/action.yml
- README.md
```
Change to GHA to only render readme if tf-docs.yml is present in module directory
Move tf-docs generation step to after checkout in composite action to save a checkout
```
> fix: only render readme if tf-docs.yml is present; move tf-docs step

- google_permissions/main.tf
- google_permissions/other_roles.tf
```
google_permissions module: for entitlements, we removed GCP "owner" IAM permissions across the board. For the short/near term, we will continue granting "owner" to the admin group. This corrects that former change. Now, regardless, admin workgroup for the specified tenant/appcode will have "owner" permissions on the projects.
We also updated the `other_roles.tf` where there was one logic error and one over-application of locking things behind constraints.
```
> fix: re-added admin for owner for all, bad logic in other_roles

- google_permissions/outputs.tf
Code in https://github.com/mozilla/terraform-modules/blob/main/google_permissions/other_roles.tf suggests this should be a role allowed to be added to `folder_roles` input
This roles absence from the locals defined here causes the error "You have specified an invalid folder role." to be raised when this option is attempted
```
fix disallowed usage of defined additional folder role`roles/bigquery.dataViewer`  as an input for `var.folder_roles` 
```
> fix: add bq dataViewer to folder_additional_roles

- .github/actions/action.yml
Once again I need to change a lightbulb https://www.youtube.com/watch?v=AbSehcT19u0
Our story begins with 2 small PRs:
- https://github.com/mozilla/terraform-modules/pull/253
- https://github.com/mozilla/terraform-modules/pull/254
Between these two PRs I noticed that:
- I wasn't able to merge my PR, because it had some unsigned commits, and this repository requires signed commits
- The generated documentation was being duplicated by terraform-docs
The reason the generated documentation was being duplicated is because most of our README.md files are missing the block delimeters `` and ``.
So the generated content will be appended at the end of the file.
Well no worries, maybe I just need to add those blocks to our existing README.md files? …
> fix(docs): Sign commits for documentation changes

- google_gke/README.md
- google_gke/cluster.tf
- google_gke/variables.tf
- google_gke/versions.tf
```
Adding control_plane_endpoints_config configuration, private access to the control plane is enabled by default, and a variable toggles public access. 
This will allow authorized users to access the control plane of our clusters without using our bastions.
```
Docs: https://cloud.google.com/blog/products/containers-kubernetes/new-dns-based-endpoint-for-the-gke-control-plane
> feat(google_gke): added configuration for control_plane_endpoints_config, updated versions and added variable to toggle

- google_monitoring/README.md
- google_monitoring/outputs.tf
To set up alerting for Yardstick, I need access to the ids of the generated checks. Instead of exposing individual fields, I decided to simply expose the checks themselves, so all attributes can be accessed.
https://mozilla-hub.atlassian.net/browse/SRELEAD-301
```
The google_monitoring module now exposes the generated uptime checks as an output.
```
> SRELEAD-301: Expose generated uptime checks in google_monitoring.

- google_permissions/other_roles.tf
- google_permissions/pam_entitlement.tf
```
- complete removal of var.entitlement_enabled from other_roles.tf - at one point there was a reason for it, but as it exists, it is breaking legitimate usage
- added  roles/secretmanager.secretAccessor and  roles/secretmanager.secretVersionAdder to default admin entitlement per OPST-1833
```
> fix(google_permissions) complete removal of var.entitlement_enabled from other_roles, add secret roles to default ent

- .github/actions/action.yml
```
Use -version:rename instead of date in CI tagging logic to avoid collisions if things get tagged out of chronological order
To prevent things like https://github.com/mozilla/terraform-modules/actions/runs/13662382521
```
> norelease: version:refname in tagging logic to avoid collisions

- google_permissions/pam_entitlement.tf
```
This pull request includes a change to the `google_permissions/pam_entitlement.tf` file. The change updates the project assignment logic for the `google_cloud_asset_project_feed` resource to differentiate between non-production and production environments.
```
> fix(google-permissions) fix loop bug in slack project_feed - OPST-1914

- google_fastly_waf/certificate.tf
- google_fastly_waf/outputs.tf
```
Allow creating a Fastly WAF without a separate subscription domain
```
> fix(fastly): Make subscription domain optional

- google_permissions/pam_entitlement.tf
```
* Added a new resource `google_project_service_identity` to create a service account for the Cloud Asset API. This ensures that the Cloud Asset API is properly set up with the necessary service account.
```
> fix(google-permissions) create cloud asset service account for PAM slack - OPST-1914

- google_gke/README.md
- google_gke/cluster.tf
- google_gke/variables.tf
```
Adding config setting for cluster autoscale behavior
Default will continue to be 'BALANCED', can specify 'OPTIMIZE_UTILIZATION' for cost savings in nonprod environments
```
> OPST-2084 Add-in config setting for cluster autoscale behavior

- google_gke/k8s_api_proxy.tf
I broke the tagging with https://github.com/mozilla/terraform-modules/pull/280 as you can see in https://github.com/mozilla/terraform-modules/tags
Put in https://github.com/mozilla/terraform-modules/pull/282 to correct the issue and trying to trigger a tag + release
```
Fixing tagging in the release process
```
> chore(google_gke): White space change to trigger tagging of new release

- google_workload_identity/README.md
- google_workload_identity/main.tf
- google_workload_identity/outputs.tf
- google_workload_identity/variables.tf
```
* Removing data source for existing google_service_account, this is failing in hashicorp/google versions 6.13+ 
* Using `gcp_sa_name` directly instead of data source 
* Adding new `gcp_sa_email` variable that can be populated for existing service accounts
```
This update requires accompanying changes to the `google_gke_tenant` module to use the service account name instead of the email for existing service accounts.
> feat(google_workload_identity): removed data source and updated outputs to use provided service account name and email

- google_gke_tenant/gke_service_account.tf
```
Pinning google_workload_identity module in google_gke_tenant to the most recent functional release. 
```
> fix(google_gke_tenant): pin gke_service_account module version

- google_workload_identity/README.md
- google_workload_identity/main.tf
- google_workload_identity/outputs.tf
- google_workload_identity/variables.tf
```
* Reverts mozilla/terraform-modules#285
```
Reverting 285 until we can pin versions in various infra repositories
> Revert "feat(google_workload_identity): removed data source and updated outputs to use provided service account name and email"

- google_monitoring/README.md
Correct documentation errors for `period` and minimum regions required. After implementing the module across a couple of projects, I've noticed a few mistakes.
```
Correct documentation errors for `period` and minimum regions required.
```
> chore(google_monitoring): Correct documentation errors.

- google_cloudsql_mysql/README.md
- google_cloudsql_mysql/main.tf
- google_cloudsql_mysql/variables.tf
```
This allows users to enable Cloud SQL Enterprise Plus on replica instances. To configure this, set `replica_edition = "ENTERPRISE_PLUS"` in upstream modules.
I also alphabetized variables.tf to make it easier to find things and explicitly defined types for each variable to get rid of warnings in IDEs.
```
> feat(google_cloudsql_mysql): add support for ENTERPRISE_PLUS on replicas

- google_cloudsql_mysql/README.md
- google_cloudsql_mysql/main.tf
- google_cloudsql_mysql/variables.tf
```
Enables data cache on replica instances if Cloud SQL Enterprise Plus is enabled.
```
> feat(google_cloudsql_mysql): enable data cache on replicas if enterprise plus

- google_cdn-external/README.md
- google_cdn-external/main.tf
- google_cdn-external/variables.tf
```
Add ability to override backend bucket name to support legacy infra
Expose `bypass_cache_on_request_headers` arg 
```
Required by, and tested in https://github.com/mozilla-it/dataservices-infra/pull/722
> feat:add ability to override name suffix

- google_cloudsql_postgres/README.md
- google_cloudsql_postgres/main.tf
- google_cloudsql_postgres/variables.tf
This implements the postgres equivalent of https://github.com/mozilla/terraform-modules/pull/291 & https://github.com/mozilla/terraform-modules/pull/295
```
This allows users to enable Cloud SQL Enterprise Plus on replica instances. To configure this, set `replica_edition = "ENTERPRISE_PLUS"` in upstream modules.
I also alphabetized variables.tf to make it easier to find things and explicitly defined types for each variable to get rid of warnings in IDEs.
```
> feat(google_cloudsql_postgres): add support for ENTERPRISE_PLUS on replicas

- google_gke_namespace_logging/README.md
- google_gke_namespace_logging/main.tf
- google_gke_namespace_logging/outputs.tf
- google_gke_namespace_logging/variables.tf
https://mozilla-hub.atlassian.net/browse/OPST-2378
When you set up a service in GCPv2 you can choose between Cloud Logging & BigQuery for storing logs.
The log sink is created in global-platform-admin, and the log sink destination is created in 
(dataservices|webservices)-infra. This split means that if you change the log sink from BigQuery to
Cloud Logging or vice versa you will lose logs written to the log sink until the log sink
destination has been created.
The fix is to always create both log sink destinations, and grant the unique writer identity
permissions to write to both.
```
Always create both log sink destinations to prevent loss of logs
```
> fix(google_gke_namespace_logging): Prevent loss of logs when modifying log sink

- google_gke_namespace_logging/main.tf
https://mozilla-hub.atlassian.net/browse/OPST-2378
Breakage from https://github.com/mozilla/terraform-modules/pull/292
Some tenants set `disable_shared_integrations: true` which prevents them from
creating a log sink with a unique service account. We should handle this case
by conditionally creating the IAM permissions if the service account is not ""
```
Allow passing empty string as service account
```
> fix(google_gke_namespace_logging): Allow passing empty string as service account

- .github/actions/action.yml
```
Change tag extraction bash to strictly grab the last 5 characters of the tag, instead of assuming the version is after the first dash. Fixes versioning CI for modules that have `-`s in them.
```
Fixes google_cdn-external builds - https://github.com/mozilla/terraform-modules/actions/runs/14646386623/job/41101547611?pr=299
> fix:update substitution to strictly grab last 5 chars

- .github/workflows/monorepo.yml
- google_cdn-external/README.md
- google_cdn-external/variables.tf
```
Give backend_bucket_name_override a default value to prevent errors if it's not provided
```
> fix:give backend_bucket_name_override a default value

- google_certificate_manager_certificate_map/README.md
- google_certificate_manager_certificate_map/certificate-map.tf
- google_certificate_manager_certificate_map/certificates.tf
- google_certificate_manager_certificate_map/data.tf
- google_certificate_manager_certificate_map/outputs.tf
- google_certificate_manager_certificate_map/variables.tf
```
* add `certificate_manager_ceritifcate_map` resource to outputs to make it's attributes readable by module users
* make `shared_infra_project_id` optional and use the provider project to build certmaps by default
```
> Google certificate manager certificate map/update

- google_gke/README.md
- google_gke/cluster.tf
- google_gke/variables.tf
```
Add configuration to enable Google Config Connector, left disabled by default.
```
https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall
> feat(google_gke): add config_connector_config block to GKE cluster resource, disabled by default

- google_fastly_waf/main.tf
- google_fastly_waf/variables.tf
```
- Adds the `ngwaf_percent_enabled` variable which configures how much traffic to send to WAF. This allows use cases where we want to entirely bypass WAF.
```
> feat(fastly): Allow setting percentage or bypass WAF by setting to 0

- google_fastly_waf/iam.tf
- google_fastly_waf/variables.tf
```
* Allow setting service_account manually, default to existing behavior of generating.
```
> feat(fastly): Allow setting service account name manually

- google_permissions/outputs.tf
Adding  cloudsql.client, cloudsql.instanceUser, cloudsql.studioUser, and cloudsql.viewer roles to `project_additional_roles`. This allows the added roles to be assigned on https://github.com/mozilla/webservices-infra/pull/6228. The terraform plan is currently failing because these roles did not previously exist.
```
Added the following roles to `project_additional_roles` :
- roles/cloudsql.client
- roles/cloudsql.instanceUser
- roles/cloudsql.studioUser
- roles/cloudsql.viewer
```
> Added CloudSQL to use in SVCSE-3162

- google_redis/README.md
- google_redis/outputs.tf
```
Adding the read_endpoint and read_endpoint_port output variables. This is to be able to output read replica host and ports in tf configurations.
for users of the affected modules!
```
> Adding read endpoint and read endpoint port to outputs

- google_redis/README.md
- google_redis/main.tf
- google_redis/variables.tf
```
Adding read_replicas_mode and replica_count variables. These were previously configured under redis_configs but now have to be configured directly in the module in redis 7_2.
for users of the affected modules!
```
> Adding read_replicas_mode and replica_count variables

- .github/PULL_REQUEST_TEMPLATE.md
- .github/pull_request_template.md
This PR adds a basic PR template matching this current PR description, as proposed [here](https://docs.google.com/document/d/1llOEaOnEppTFbXkk76aicYpqwysFQ659BGdOFm6ISq8/edit?usp=sharing).
* SVCSE-3434
> chore: Add simple PR template.

- google_redis/README.md
- google_redis/variables.tf
https://github.com/mozilla/terraform-modules/pull/323 was a breaking change because the default values only work for BASIC tier instances.
Tested in https://github.com/mozilla/webservices-infra/pull/6680
* MZCLD-724
> fix(google_redis): Defaults for replica_count and read_replicas_mode vary on tier

- google_fastly_waf/main.tf
The empty string is an invalid value for the Fastly snippet priority, since it needs to be a number. By setting the default value to `null`, we pretend the priority isn't set at all, so the upstream default value of 100 is used.
This came up in https://github.com/mozilla/webservices-infra/pull/6761.
> fix(google_fastly_waf): The priority of a snippet can't be a string.

- google_permissions/pam_entitlement.tf
There are some tenants that do not use a workgroup named the same as the tenant.
These tenants use .globals.extra_attributes.workgroup to specify the workgroup
with permissions to operate the service.
This module assumed that the workgroup would always match the tenant.
This PR uses developer workgroups for the default admin entitlement.
* MZCLD-782
* https://github.com/mozilla/webservices-infra/pull/6855 PR where this bug was found
> fix(google_permissions): Use developer workgroups for default admin entitlement

- google_cloudsql_postgres/README.md
- google_cloudsql_postgres/main.tf
- google_cloudsql_postgres/variables.tf
This PR adds 4 variables for compatibility with Google Google Database Migration Service:
- `backup_configuration_enabled` because DMS sets `enabled = false`
- `backup_configuration_location` because DMS sets `location = null`
- `point_in_time_recovery_enabled` because DMS sets `point_in_time_recovery_enabled = false`
- `user_labels` because DMS adds `"goog-dms-instance" = "true"`
* SVCSE-3324
* SVCSE-3327
* https://github.com/mozilla/webservices-infra/pull/7167
> feat(google_cloudsql_postgres): Add variables for compatibility with Google Database Migration Service

- .github/workflows/monorepo.yml
download-artifacts 5.0 has a breaking change w/r/t how it handles filepaths when dealing with multiple artifacts that breaks the comment & release portions of CI in this repo. This downgrade will unblock releases while I work on updating the workflows to handle this new behavior.
* Example of a PR with the broken comment - https://github.com/mozilla/terraform-modules/pull/370#issuecomment-3300271863
* Validated that the downgrade fixes commenting in https://github.com/mozilla/terraform-modules/pull/371
> fix(ci): downgrade artifact download to 4.3.0

- google_project/README.md
- google_project/main.tf
- google_project/variables.tf
See https://mozilla-hub.atlassian.net/browse/MZCLD-1027. My plan is to keep the module default the [GCP default](https://github.com/mozilla/terraform-modules/pull/370) and set the actual default in the functional repos according to our retention policies.
* MZCLD-1027
> feat(google_project): allow specifying default bucket log retention

- google_fastly_waf/main.tf
We started seeing a failing health check in telescope, showing that `application/geo+json` was not being compressed in our CDN. Adding this mime type explicitly so it will be compressed going forward.
```sh
curl -I "https://firefox-settings-attachments.cdn.allizom.org/main-workspace/regions/ad99625f-7ec0-4fc4-a44d-07afe8f3ed91.geojson" -H "Accept-Encoding:br"
HTTP/2 200
content-type: application/geo+json
x-guploader-uploadid: AAwnv3KSMmmRRHzWMlyeHjxEp6r-7ZWqmJ_bI1V-fqy8rqPc9e1PN4_dXGpQJE_8hiR9EzwXQI8JK4o
expires: Mon, 22 Sep 2025 16:17:22 GMT
cache-control: public, max-age=3600
last-modified: Thu, 09 Mar 2023 14:08:02 GMT
etag: "daf1d4857d52bde47a293fbbe1fea035"
x-goog-generation: 1678370882119543
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity …
```
> fix(fastly): Add application/geo+json mime type to compression list
